export interface Pillar {
  slug: string;
  name: string;
  description: string;
  metaDescription: string;
  relatedPillars: string[];
}

export interface Article {
  id: number;
  title: string;
  slug: string;
  pillar: string;
  targetKeyword: string;
  intent: "INFO" | "COMM" | "TRANS";
  difficulty: "Low" | "Low-Med" | "Med" | "Med-High" | "High";
  format: "guide" | "calculator" | "comparison-table" | "decision-table" | "data-table";
  priorityTier: "A" | "B" | "C";
  estVolume: string;
  costLow: string;
  costAvg: string;
  costHigh: string;
  costUnit: string;
  costSource: string;
  metaDescription: string;
  datePublished: string;
  dateModified: string;
}

export interface AffiliateLink {
  name: string;
  url: string;
  description: string;
  relevantPillars: string[];
}

export const pillars: Pillar[] = [
  {
    slug: "roofing-exterior",
    name: "Roofing & Exterior",
    description: "Cost guides for roofing, siding, gutters, driveways, decks, fencing, and exterior painting. Get accurate pricing for your home's exterior projects.",
    metaDescription: "Compare real roofing, siding, gutter, and exterior project costs. Get 2026 price ranges before you hire a contractor.",
    relatedPillars: ["home-maintenance", "hvac-energy"],
  },
  {
    slug: "hvac-energy",
    name: "HVAC & Energy",
    description: "Heating, cooling, insulation, solar, and utility bill guides. Find out what it really costs to keep your home comfortable and energy-efficient.",
    metaDescription: "See real HVAC, insulation, solar, and utility costs. Compare 2026 prices for heating, cooling, and energy projects.",
    relatedPillars: ["interior-renovation", "plumbing"],
  },
  {
    slug: "plumbing",
    name: "Plumbing & Water Systems",
    description: "Water heater replacement, repiping, sewer and septic costs, and water bill guides. Everything you need to budget for plumbing work.",
    metaDescription: "Browse plumbing cost guides: water heater, repiping, sewer, septic, and water bills. Get 2026 price ranges for your project.",
    relatedPillars: ["kitchen-bath", "home-maintenance"],
  },
  {
    slug: "electrical",
    name: "Electrical",
    description: "Panel upgrades, rewiring, generators, EV chargers, and lighting costs. Know what electricians charge before you hire.",
    metaDescription: "Compare electrical project costs: panel upgrades, rewiring, generators, EV chargers. Know what electricians charge in 2026.",
    relatedPillars: ["kitchen-bath", "hvac-energy"],
  },
  {
    slug: "kitchen-bath",
    name: "Kitchen & Bathroom Remodeling",
    description: "Kitchen remodels, bathroom remodels, cabinets, and countertop costs. Plan your dream renovation with real-world pricing.",
    metaDescription: "Browse kitchen and bathroom remodeling costs for 2026. See real pricing for cabinets, countertops, and full renovations.",
    relatedPillars: ["interior-renovation", "electrical"],
  },
  {
    slug: "interior-renovation",
    name: "Flooring, Painting & Interior Renovation",
    description: "Flooring, interior painting, basement finishing, drywall, and home addition costs. Budget for your interior improvement projects.",
    metaDescription: "See real flooring, painting, basement finishing, and interior renovation costs. Budget with confidence using 2026 pricing.",
    relatedPillars: ["kitchen-bath", "hvac-energy"],
  },
  {
    slug: "home-maintenance",
    name: "Home Maintenance & Repair Decisions",
    description: "Appliances, mold, pest control, tree removal, insurance, and repair-vs-replace guides. Make smarter home maintenance decisions.",
    metaDescription: "Compare repair vs. replace costs for appliances, mold, pest control, tree removal, and home maintenance projects.",
    relatedPillars: ["roofing-exterior", "plumbing"],
  },
];

export const articles: Article[] = [
  { id: 1, title: "Roof Replacement Cost: 2026 Price Guide by Size & Material", slug: "roof-replacement-cost", pillar: "roofing-exterior", targetKeyword: "roof replacement cost", intent: "COMM", difficulty: "High", format: "calculator", priorityTier: "A", estVolume: "40K/mo", costLow: "$5,700", costAvg: "$10,800", costHigh: "$16,000", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "Roof replacement costs $5,700\u2013$16,000 nationally, averaging $10,800. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 2, title: "Roof Repair vs. Replacement: How to Decide", slug: "roof-repair-vs-replacement", pillar: "roofing-exterior", targetKeyword: "roof repair vs replacement", intent: "COMM", difficulty: "Med", format: "decision-table", priorityTier: "A", estVolume: "3K/mo", costLow: "$350", costAvg: "$850", costHigh: "$1,500", costUnit: " for repair", costSource: "Angi 2026", metaDescription: "Not sure whether to repair or replace? See real cost data ($350\u2013$1,500 for repair) and a decision guide to help you choose.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 3, title: "HVAC Repair vs. Replace: The $5,000 Rule Explained", slug: "hvac-repair-vs-replace", pillar: "hvac-energy", targetKeyword: "hvac repair vs replace calculator", intent: "COMM", difficulty: "Med", format: "calculator", priorityTier: "A", estVolume: "4K/mo", costLow: "$150", costAvg: "$500", costHigh: "$3,000", costUnit: " for repair", costSource: "HVAC Pricing Guide 2026", metaDescription: "HVAC repair costs $150\u2013$3,000 for repair nationally, averaging $500 for repair. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 4, title: "How Much Does a New HVAC System Cost? (2026)", slug: "new-hvac-system-cost", pillar: "hvac-energy", targetKeyword: "cost to install a new hvac system", intent: "COMM", difficulty: "Med-High", format: "calculator", priorityTier: "A", estVolume: "15K/mo", costLow: "$8,000", costAvg: "$11,500", costHigh: "$15,000", costUnit: "", costSource: "ConsumerAffairs 2026 & 5Estimates", metaDescription: "New HVAC system costs $8,000\u2013$15,000 nationally, averaging $11,500. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 5, title: "Cost to Replace a Water Heater (Tank vs. Tankless)", slug: "cost-to-replace-water-heater", pillar: "plumbing", targetKeyword: "cost to replace water heater", intent: "COMM", difficulty: "Med", format: "comparison-table", priorityTier: "A", estVolume: "20K/mo", costLow: "$600", costAvg: "$1,800", costHigh: "$3,100", costUnit: " for tank", costSource: "HomeGuide 2026 & NerdWallet 2026", metaDescription: "Compare costs: cost to replace water heater ranges from $600 to $3,100 for tank, averaging $1,800 for tank. See the full cost breakdown by option.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 6, title: "Average Kitchen Remodel Cost: 2026 Budget Breakdown", slug: "average-kitchen-remodel-cost", pillar: "kitchen-bath", targetKeyword: "average cost of kitchen remodel", intent: "COMM", difficulty: "High", format: "calculator", priorityTier: "A", estVolume: "30K/mo", costLow: "$15,000", costAvg: "$27,000", costHigh: "$45,000", costUnit: "", costSource: "Fixr 2026 & Remodeling Magazine 2025", metaDescription: "Kitchen remodel costs $15,000\u2013$45,000 nationally, averaging $27,000. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 7, title: "Bathroom Remodel Cost by Size (Half, Full, Primary)", slug: "bathroom-remodel-cost-by-size", pillar: "kitchen-bath", targetKeyword: "cost to remodel a bathroom", intent: "COMM", difficulty: "Med-High", format: "calculator", priorityTier: "A", estVolume: "18K/mo", costLow: "$6,500", costAvg: "$12,000", costHigh: "$25,000", costUnit: "", costSource: "Angi 2026 & This Old House 2026", metaDescription: "Bathroom remodel costs $6,500\u2013$25,000 nationally, averaging $12,000. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 8, title: "Cost to Finish a Basement (With & Without a Bathroom)", slug: "cost-to-finish-a-basement", pillar: "interior-renovation", targetKeyword: "cost to finish a basement", intent: "COMM", difficulty: "Med", format: "calculator", priorityTier: "A", estVolume: "12K/mo", costLow: "$15,000", costAvg: "$32,000", costHigh: "$75,000", costUnit: "", costSource: "HomeGuide 2026", metaDescription: "Basement finishing costs $15,000\u2013$75,000 nationally, averaging $32,000. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 9, title: "Is It Worth It to Replace Your Windows?", slug: "is-it-worth-it-to-replace-windows", pillar: "home-maintenance", targetKeyword: "is it worth it to replace windows", intent: "COMM", difficulty: "Low-Med", format: "decision-table", priorityTier: "A", estVolume: "2K/mo", costLow: "$400", costAvg: "$775", costHigh: "$1,300", costUnit: " per window", costSource: "This Old House 2026", metaDescription: "Not sure whether to repair or replace? See real cost data ($400\u2013$1,300 per window) and a decision guide to help you choose.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 10, title: "Cost to Repipe a House: PEX vs. Copper", slug: "cost-to-repipe-a-house-pex-vs-copper", pillar: "plumbing", targetKeyword: "cost to repipe a house with pex", intent: "COMM", difficulty: "Low", format: "comparison-table", priorityTier: "A", estVolume: "3K/mo", costLow: "$4,000", costAvg: "$7,500", costHigh: "$15,000", costUnit: " for PEX", costSource: "Angi 2026", metaDescription: "Compare costs: cost to repipe a house with pex ranges from $4,000 to $15,000 for PEX, averaging $7,500 for PEX. See the full cost breakdown by option.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 11, title: "Cost to Replace an Electrical Panel (100A vs. 200A)", slug: "cost-to-replace-electrical-panel", pillar: "electrical", targetKeyword: "cost to replace electrical panel", intent: "COMM", difficulty: "Low-Med", format: "comparison-table", priorityTier: "A", estVolume: "8K/mo", costLow: "$1,200", costAvg: "$2,500", costHigh: "$4,000", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "Compare costs: cost to replace electrical panel ranges from $1,200 to $4,000, averaging $2,500. See the full cost breakdown by option.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 12, title: "Average Utility Bill by Household Size: Electric", slug: "average-electric-bill-by-household-size", pillar: "hvac-energy", targetKeyword: "average electric bill by household size", intent: "INFO", difficulty: "Low", format: "data-table", priorityTier: "A", estVolume: "25K/mo", costLow: "$100", costAvg: "$150", costHigh: "$250", costUnit: "/month", costSource: "BLS Consumer Expenditure Survey 2025", metaDescription: "See average costs by category: average electric bill by household size, ranging from $100 to $250/month. Sourced data, updated for 2026.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 13, title: "Cost to Install Solar Panels (With & Without Battery)", slug: "cost-to-install-solar-panels", pillar: "hvac-energy", targetKeyword: "cost to install solar panels", intent: "COMM", difficulty: "Med-High", format: "calculator", priorityTier: "A", estVolume: "15K/mo", costLow: "$15,000", costAvg: "$25,000", costHigh: "$35,000", costUnit: " after credits", costSource: "EnergySage 2026", metaDescription: "Solar panel installation costs $15,000\u2013$35,000 after credits nationally, averaging $25,000 after credits. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 14, title: "Furnace Repair vs. Replace: Cost & Decision Guide", slug: "furnace-repair-vs-replace", pillar: "hvac-energy", targetKeyword: "furnace repair vs replace", intent: "COMM", difficulty: "Low", format: "decision-table", priorityTier: "A", estVolume: "2K/mo", costLow: "$100", costAvg: "$500", costHigh: "$1,500", costUnit: " for repair", costSource: "HVAC Pricing Guide 2026", metaDescription: "Not sure whether to repair or replace? See real cost data ($100\u2013$1,500 for repair) and a decision guide to help you choose.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 15, title: "Mold Remediation Cost by Square Footage", slug: "mold-remediation-cost-by-square-footage", pillar: "home-maintenance", targetKeyword: "mold remediation cost per square foot", intent: "COMM", difficulty: "Low-Med", format: "calculator", priorityTier: "A", estVolume: "5K/mo", costLow: "$1,500", costAvg: "$4,500", costHigh: "$8,000", costUnit: "", costSource: "Angi 2026 & HomeGuide 2026", metaDescription: "Mold remediation costs $1,500\u2013$8,000 nationally, averaging $4,500. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 16, title: "Cost to Replace Windows (Per Window & Whole House)", slug: "cost-to-replace-windows", pillar: "roofing-exterior", targetKeyword: "cost to replace windows", intent: "COMM", difficulty: "High", format: "calculator", priorityTier: "B", estVolume: "22K/mo", costLow: "$400", costAvg: "$775", costHigh: "$1,300", costUnit: " per window", costSource: "This Old House 2026", metaDescription: "Window replacement costs $400\u2013$1,300 per window nationally, averaging $775 per window. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 17, title: "Cost to Paint a House: Interior vs. Exterior", slug: "cost-to-paint-a-house", pillar: "interior-renovation", targetKeyword: "cost to paint a house", intent: "COMM", difficulty: "Med", format: "comparison-table", priorityTier: "B", estVolume: "14K/mo", costLow: "$1,500", costAvg: "$3,500", costHigh: "$6,000", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "Compare costs: cost to paint a house ranges from $1,500 to $6,000, averaging $3,500. See the full cost breakdown by option.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 18, title: "Cost to Replace Flooring by Type (LVP, Hardwood, Tile, Carpet)", slug: "cost-to-replace-flooring-by-type", pillar: "interior-renovation", targetKeyword: "cost to replace flooring per square foot", intent: "COMM", difficulty: "Med", format: "comparison-table", priorityTier: "B", estVolume: "10K/mo", costLow: "$3", costAvg: "$8", costHigh: "$15", costUnit: "/sq ft", costSource: "HomeGuide 2026 & Fixr 2026", metaDescription: "Compare costs: cost to replace flooring per square foot ranges from $3 to $15/sq ft, averaging $8/sq ft. See the full cost breakdown by option.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 19, title: "Cost to Install a Fence (By Material & Length)", slug: "cost-to-install-a-fence", pillar: "roofing-exterior", targetKeyword: "cost to install a fence", intent: "COMM", difficulty: "Med", format: "calculator", priorityTier: "B", estVolume: "12K/mo", costLow: "$1,500", costAvg: "$3,500", costHigh: "$8,000", costUnit: "", costSource: "HomeGuide 2026 & Fixr 2026", metaDescription: "Fence installation costs $1,500\u2013$8,000 nationally, averaging $3,500. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 20, title: "Cost to Remove a Tree (and Stump Grinding)", slug: "cost-to-remove-a-tree", pillar: "home-maintenance", targetKeyword: "cost to remove a tree", intent: "COMM", difficulty: "Low-Med", format: "calculator", priorityTier: "B", estVolume: "9K/mo", costLow: "$200", costAvg: "$700", costHigh: "$2,000", costUnit: "", costSource: "Angi 2026 & HomeGuide 2026", metaDescription: "Tree removal costs $200\u2013$2,000 nationally, averaging $700. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 21, title: "Average Cost of Homeowners Insurance (What Drives It Up)", slug: "average-cost-of-homeowners-insurance", pillar: "home-maintenance", targetKeyword: "average cost of homeowners insurance", intent: "INFO", difficulty: "High", format: "data-table", priorityTier: "B", estVolume: "60K/mo", costLow: "$1,000", costAvg: "$1,500", costHigh: "$3,000", costUnit: "/year", costSource: "NAIC 2024 & Bankrate 2026", metaDescription: "See average costs by category: average cost of homeowners insurance, ranging from $1,000 to $3,000/year. Sourced data, updated for 2026.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 22, title: "Cost to Install Attic Insulation", slug: "cost-to-install-attic-insulation", pillar: "hvac-energy", targetKeyword: "cost to install attic insulation", intent: "COMM", difficulty: "Low", format: "calculator", priorityTier: "B", estVolume: "6K/mo", costLow: "$1,500", costAvg: "$3,500", costHigh: "$6,000", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "Attic insulation costs $1,500\u2013$6,000 nationally, averaging $3,500. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 23, title: "AC Repair vs. Replace: When to Stop Paying for Repairs", slug: "ac-repair-vs-replace", pillar: "hvac-energy", targetKeyword: "ac repair vs replace", intent: "COMM", difficulty: "Med", format: "decision-table", priorityTier: "B", estVolume: "4K/mo", costLow: "$150", costAvg: "$400", costHigh: "$3,000", costUnit: " for repair", costSource: "HVAC Pricing Guide 2026", metaDescription: "Not sure whether to repair or replace? See real cost data ($150\u2013$3,000 for repair) and a decision guide to help you choose.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 24, title: "Cost to Install a Generator (Standby vs. Portable)", slug: "cost-to-install-a-generator", pillar: "electrical", targetKeyword: "cost to install a generator", intent: "COMM", difficulty: "Low-Med", format: "comparison-table", priorityTier: "B", estVolume: "5K/mo", costLow: "$500", costAvg: "$3,500", costHigh: "$8,000", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "Compare costs: cost to install a generator ranges from $500 to $8,000, averaging $3,500. See the full cost breakdown by option.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 25, title: "Refrigerator Repair vs. Replace: The Real Cost Math", slug: "refrigerator-repair-vs-replace", pillar: "home-maintenance", targetKeyword: "is it worth it to replace a refrigerator", intent: "COMM", difficulty: "Low", format: "decision-table", priorityTier: "B", estVolume: "3K/mo", costLow: "$150", costAvg: "$400", costHigh: "$1,000", costUnit: " for repair", costSource: "Angi 2026 & Fixr 2026", metaDescription: "Not sure whether to repair or replace? See real cost data ($150\u2013$1,000 for repair) and a decision guide to help you choose.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 26, title: "Cost to Install an EV Charger at Home", slug: "cost-to-install-ev-charger", pillar: "electrical", targetKeyword: "cost to install ev charger", intent: "COMM", difficulty: "Med", format: "calculator", priorityTier: "B", estVolume: "8K/mo", costLow: "$500", costAvg: "$1,500", costHigh: "$2,500", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "EV charger installation costs $500\u2013$2,500 nationally, averaging $1,500. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 27, title: "Gutter Installation & Replacement Cost", slug: "gutter-installation-cost", pillar: "roofing-exterior", targetKeyword: "gutter installation cost", intent: "COMM", difficulty: "Low-Med", format: "calculator", priorityTier: "B", estVolume: "7K/mo", costLow: "$1,000", costAvg: "$2,500", costHigh: "$5,000", costUnit: "", costSource: "HomeGuide 2026 & Fixr 2026", metaDescription: "Gutter installation costs $1,000\u2013$5,000 nationally, averaging $2,500. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 28, title: "Metal Roof vs. Asphalt Shingle Roof: Cost & Lifespan Compared", slug: "metal-roof-vs-asphalt-shingle", pillar: "roofing-exterior", targetKeyword: "metal roof vs asphalt shingle cost", intent: "COMM", difficulty: "Med", format: "comparison-table", priorityTier: "B", estVolume: "4K/mo", costLow: "$5,700", costAvg: "$12,000", costHigh: "$25,000", costUnit: "", costSource: "HomeGuide 2026", metaDescription: "Compare costs: metal roof vs asphalt shingle cost ranges from $5,700 to $25,000, averaging $12,000. See the full cost breakdown by option.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 29, title: "Cost to Build a Deck (By Material & Size)", slug: "cost-to-build-a-deck", pillar: "roofing-exterior", targetKeyword: "cost to build a deck", intent: "COMM", difficulty: "Med-High", format: "calculator", priorityTier: "B", estVolume: "18K/mo", costLow: "$3,500", costAvg: "$7,500", costHigh: "$15,000", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "Deck building costs $3,500\u2013$15,000 nationally, averaging $7,500. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 30, title: "Average Water Bill by Household Size", slug: "average-water-bill-by-household-size", pillar: "plumbing", targetKeyword: "average water bill by household size", intent: "INFO", difficulty: "Low", format: "data-table", priorityTier: "B", estVolume: "15K/mo", costLow: "$35", costAvg: "$75", costHigh: "$150", costUnit: "/month", costSource: "EPA WaterSense 2025", metaDescription: "See average costs by category: average water bill by household size, ranging from $35 to $150/month. Sourced data, updated for 2026.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 31, title: "Cost to Repair vs. Replace a Garage Door", slug: "garage-door-repair-vs-replace", pillar: "home-maintenance", targetKeyword: "garage door repair vs replace", intent: "COMM", difficulty: "Low", format: "decision-table", priorityTier: "B", estVolume: "3K/mo", costLow: "$150", costAvg: "$350", costHigh: "$1,000", costUnit: " for repair", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "Not sure whether to repair or replace? See real cost data ($150\u2013$1,000 for repair) and a decision guide to help you choose.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 32, title: "Cost to Install a Whole-House Generator vs. Battery Backup", slug: "generator-vs-battery-backup-cost", pillar: "electrical", targetKeyword: "generator vs battery backup cost", intent: "COMM", difficulty: "Low", format: "comparison-table", priorityTier: "B", estVolume: "2K/mo", costLow: "$500", costAvg: "$5,000", costHigh: "$15,000", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "Compare costs: generator vs battery backup cost ranges from $500 to $15,000, averaging $5,000. See the full cost breakdown by option.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 33, title: "Cost to Remodel a Kitchen Without New Appliances", slug: "kitchen-remodel-cost-without-appliances", pillar: "kitchen-bath", targetKeyword: "kitchen remodel cost without appliances", intent: "COMM", difficulty: "Low", format: "guide", priorityTier: "B", estVolume: "4K/mo", costLow: "$10,000", costAvg: "$20,000", costHigh: "$35,000", costUnit: "", costSource: "Fixr 2026 & HomeGuide 2026", metaDescription: "A complete cost guide covering kitchen remodel cost without appliances: national averages, price ranges ($10,000\u2013$35,000), and what affects your price.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 34, title: "Small Bathroom Remodel Cost (Under 40 Sq Ft)", slug: "small-bathroom-remodel-cost", pillar: "kitchen-bath", targetKeyword: "small bathroom remodel cost", intent: "COMM", difficulty: "Med", format: "calculator", priorityTier: "B", estVolume: "6K/mo", costLow: "$4,500", costAvg: "$7,500", costHigh: "$12,000", costUnit: "", costSource: "Badeloft 2026 & Angi 2026", metaDescription: "Small bathroom remodel costs $4,500\u2013$12,000 nationally, averaging $7,500. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 35, title: "Cost to Replace a Septic Tank or Repair a Sewer Line", slug: "sewer-line-repair-cost", pillar: "plumbing", targetKeyword: "sewer line repair cost", intent: "COMM", difficulty: "Med", format: "comparison-table", priorityTier: "B", estVolume: "6K/mo", costLow: "$2,500", costAvg: "$6,000", costHigh: "$12,000", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "Compare costs: sewer line repair cost ranges from $2,500 to $12,000, averaging $6,000. See the full cost breakdown by option.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 36, title: "Cost to Add a Bathroom to a Basement", slug: "cost-to-add-bathroom-to-basement", pillar: "interior-renovation", targetKeyword: "cost to finish a basement and add a bathroom", intent: "COMM", difficulty: "Low", format: "guide", priorityTier: "C", estVolume: "2K/mo", costLow: "$5,000", costAvg: "$12,000", costHigh: "$25,000", costUnit: "", costSource: "HomeGuide 2026 & Fixr 2026", metaDescription: "A complete cost guide covering cost to finish a basement and add a bathroom: national averages, price ranges ($5,000\u2013$25,000), and what affects your price.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 37, title: "Cost to Remove and Install New Attic Insulation", slug: "remove-and-install-attic-insulation", pillar: "hvac-energy", targetKeyword: "cost to remove and install attic insulation", intent: "COMM", difficulty: "Low", format: "guide", priorityTier: "C", estVolume: "1.5K/mo", costLow: "$2,000", costAvg: "$4,500", costHigh: "$8,000", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "A complete cost guide covering cost to remove and install attic insulation: national averages, price ranges ($2,000\u2013$8,000), and what affects your price.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 38, title: "Is It Worth It to Replace Your Garage Door Before Selling?", slug: "garage-door-worth-it-before-selling", pillar: "home-maintenance", targetKeyword: "is it worth replacing garage door before selling", intent: "COMM", difficulty: "Low", format: "guide", priorityTier: "C", estVolume: "1K/mo", costLow: "$800", costAvg: "$1,500", costHigh: "$3,000", costUnit: "", costSource: "Remodeling Magazine 2025", metaDescription: "A complete cost guide covering is it worth replacing garage door before selling: national averages, price ranges ($800\u2013$3,000), and what affects your price.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 39, title: "Cost to Install a Water Softener", slug: "cost-to-install-water-softener", pillar: "plumbing", targetKeyword: "cost to install a water softener", intent: "COMM", difficulty: "Low-Med", format: "calculator", priorityTier: "C", estVolume: "5K/mo", costLow: "$500", costAvg: "$1,500", costHigh: "$3,000", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "Water softener installation costs $500\u2013$3,000 nationally, averaging $1,500. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 40, title: "Cost to Replace Interior Doors", slug: "cost-to-replace-interior-doors", pillar: "interior-renovation", targetKeyword: "cost to replace interior doors", intent: "COMM", difficulty: "Low", format: "calculator", priorityTier: "C", estVolume: "6K/mo", costLow: "$100", costAvg: "$350", costHigh: "$800", costUnit: " per door", costSource: "HomeGuide 2026 & Fixr 2026", metaDescription: "Interior door replacement costs $100\u2013$800 per door nationally, averaging $350 per door. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 41, title: "Cost to Repair vs. Replace Drywall (Water/Mold Damage)", slug: "drywall-repair-vs-replace-cost", pillar: "interior-renovation", targetKeyword: "drywall repair vs replace cost", intent: "COMM", difficulty: "Low", format: "decision-table", priorityTier: "C", estVolume: "3K/mo", costLow: "$200", costAvg: "$600", costHigh: "$1,500", costUnit: " per room", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "Not sure whether to repair or replace? See real cost data ($200\u2013$1,500 per room) and a decision guide to help you choose.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 42, title: "Cost to Install Central Air in a House Without Ductwork", slug: "cost-to-install-central-air-without-ducts", pillar: "hvac-energy", targetKeyword: "cost to install central air without ducts", intent: "COMM", difficulty: "Med", format: "guide", priorityTier: "C", estVolume: "4K/mo", costLow: "$6,000", costAvg: "$12,000", costHigh: "$20,000", costUnit: "", costSource: "HomeGuide 2026", metaDescription: "A complete cost guide covering cost to install central air without ducts: national averages, price ranges ($6,000\u2013$20,000), and what affects your price.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 43, title: "Cost to Replace a Driveway (Asphalt vs. Concrete vs. Pavers)", slug: "cost-to-replace-a-driveway", pillar: "roofing-exterior", targetKeyword: "cost to replace a driveway", intent: "COMM", difficulty: "Med", format: "calculator", priorityTier: "C", estVolume: "10K/mo", costLow: "$3,000", costAvg: "$6,000", costHigh: "$12,000", costUnit: "", costSource: "HomeGuide 2026 & Fixr 2026", metaDescription: "Driveway replacement costs $3,000\u2013$12,000 nationally, averaging $6,000. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 44, title: "Termite & Pest Damage Repair Cost", slug: "termite-damage-repair-cost", pillar: "home-maintenance", targetKeyword: "termite damage repair cost", intent: "COMM", difficulty: "Low-Med", format: "calculator", priorityTier: "C", estVolume: "5K/mo", costLow: "$500", costAvg: "$3,000", costHigh: "$8,000", costUnit: "", costSource: "Angi 2026 & HomeGuide 2026", metaDescription: "Termite damage repair costs $500\u2013$8,000 nationally, averaging $3,000. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 45, title: "Cost to Upgrade a Home to 200-Amp Electrical Service", slug: "cost-to-upgrade-to-200-amp-panel", pillar: "electrical", targetKeyword: "cost to upgrade to 200 amp panel", intent: "COMM", difficulty: "Low", format: "guide", priorityTier: "C", estVolume: "4K/mo", costLow: "$1,500", costAvg: "$2,500", costHigh: "$4,000", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "A complete cost guide covering cost to upgrade to 200 amp panel: national averages, price ranges ($1,500\u2013$4,000), and what affects your price.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 46, title: "Cost to Replace Cabinets (Reface vs. Full Replace)", slug: "cabinet-refacing-vs-replacement-cost", pillar: "kitchen-bath", targetKeyword: "cabinet refacing vs replacement cost", intent: "COMM", difficulty: "Low", format: "comparison-table", priorityTier: "C", estVolume: "3K/mo", costLow: "$1,500", costAvg: "$5,000", costHigh: "$15,000", costUnit: "", costSource: "HomeGuide 2026 & Fixr 2026", metaDescription: "Compare costs: cabinet refacing vs replacement cost ranges from $1,500 to $15,000, averaging $5,000. See the full cost breakdown by option.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 47, title: "Cost to Replace Countertops (Laminate vs. Quartz vs. Granite)", slug: "cost-to-replace-countertops", pillar: "kitchen-bath", targetKeyword: "cost to replace countertops", intent: "COMM", difficulty: "Med", format: "calculator", priorityTier: "C", estVolume: "8K/mo", costLow: "$2,000", costAvg: "$4,500", costHigh: "$10,000", costUnit: "", costSource: "HomeGuide 2026 & Angi 2026", metaDescription: "Countertop replacement costs $2,000\u2013$10,000 nationally, averaging $4,500. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 48, title: "How Much Value Does a Deck/Patio/Pool Add to Your Home?", slug: "how-much-value-does-a-pool-add", pillar: "home-maintenance", targetKeyword: "how much value does a pool add to your home", intent: "INFO", difficulty: "Low", format: "data-table", priorityTier: "C", estVolume: "3K/mo", costLow: "$30,000", costAvg: "$55,000", costHigh: "$80,000", costUnit: "", costSource: "Remodeling Magazine 2025", metaDescription: "See average costs by category: how much value does a pool add to your home, ranging from $30,000 to $80,000. Sourced data, updated for 2026.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 49, title: "Cost to Reface vs. Replace Kitchen Cabinets (ROI Breakdown)", slug: "is-a-kitchen-remodel-worth-it", pillar: "kitchen-bath", targetKeyword: "is a kitchen remodel worth it", intent: "COMM", difficulty: "Low-Med", format: "guide", priorityTier: "C", estVolume: "4K/mo", costLow: "$27,000", costAvg: "$45,000", costHigh: "$79,000", costUnit: "", costSource: "Remodeling Magazine 2025", metaDescription: "A complete cost guide covering is a kitchen remodel worth it: national averages, price ranges ($27,000\u2013$79,000), and what affects your price.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
  { id: 50, title: "Home Maintenance Cost Calculator: What to Budget Per Year", slug: "annual-home-maintenance-cost-calculator", pillar: "home-maintenance", targetKeyword: "annual home maintenance cost calculator", intent: "INFO", difficulty: "Low", format: "calculator", priorityTier: "C", estVolume: "6K/mo", costLow: "$2,000", costAvg: "$4,500", costHigh: "$8,000", costUnit: "/year", costSource: "Angi 2026", metaDescription: "Home maintenance costs $2,000\u2013$8,000/year nationally, averaging $4,500/year. Use our free calculator to estimate your project cost.", datePublished: "2026-01-15", dateModified: "2026-01-15" },
];

export const affiliateLinks: AffiliateLink[] = [
  { name: "Angi Leads", url: "https://www.angi.com/", description: "Find local home service pros", relevantPillars: ["roofing-exterior", "hvac-energy", "plumbing", "electrical", "home-maintenance"] },
  { name: "Home Depot", url: "https://www.homedepot.com/", description: "DIY materials and tools", relevantPillars: ["roofing-exterior", "hvac-energy", "interior-renovation", "kitchen-bath"] },
  { name: "Amazon Associates", url: "https://www.amazon.com/", description: "Tools and hardware", relevantPillars: ["home-maintenance", "hvac-energy", "plumbing"] },
  { name: "Policygenius", url: "https://www.policygenius.com/", description: "Homeowners insurance comparison", relevantPillars: ["home-maintenance"] },
  { name: "SoFi Home Improvement Loans", url: "https://www.sofi.com/home-improvement-loans/", description: "Home improvement financing", relevantPillars: ["kitchen-bath", "interior-renovation", "roofing-exterior"] },
];

export function getPillar(slug: string): Pillar | undefined {
  return pillars.find((p) => p.slug === slug);
}

export function getArticlesByPillar(pillarSlug: string): Article[] {
  return articles.filter((a) => a.pillar === pillarSlug);
}

export function getArticle(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}

export function getArticlesByTier(tier: "A" | "B" | "C"): Article[] {
  return articles.filter((a) => a.priorityTier === tier);
}

export function getRelatedArticles(article: Article, count: number = 3): Article[] {
  const candidates = articles.filter((a) => a.pillar === article.pillar && a.slug !== article.slug);
  const sameFormat = candidates.filter((a) => a.format === article.format);
  const rest = candidates.filter((a) => a.format !== article.format);
  return [...sameFormat, ...rest].slice(0, count);
}
